var esp=msg.payload;
var msg2 = {};
global.set('nodemcu',esp);
var svett=global.get('nodemcu["192.168.1.61"].Sensors[6].TaskValues[0].Value');
var svetCookk=global.get('nodemcu["192.168.1.61"].Sensors[6].TaskValues[1].Value');
var tempKk=global.get('nodemcu["192.168.1.61"].Sensors[8].TaskValues[0].Value');
var humii=global.get('nodemcu["192.168.1.61"].Sensors[8].TaskValues[1].Value');
var oknoo=global.get('nodemcu["192.168.1.68"].Sensors[7].TaskValues[0].Value');
var utroo=global.get('nodemcu["192.168.1.68"].Sensors[7].TaskValues[1].Value');
var temaa=global.get('nodemcu["192.168.1.66"].Sensors[5].TaskValues[0].Value');
var pirk=global.get('nodemcu["192.168.1.61"].Sensors[4].TaskValues[0].Value');
var ventVv=global.get('nodemcu["192.168.1.66"].Sensors[5].TaskValues[2].Value');
var luxk=global.get('nodemcu["192.168.1.61"].Sensors[7].TaskValues[0].Value');
var coo=global.get('nodemcu["192.168.1.69"].Sensors[11].TaskValues[0].Value');
var tempInn=global.get('nodemcu["192.168.1.67"].Sensors[5].TaskValues[0].Value');
var tempOutt=global.get('nodemcu["192.168.1.68"].Sensors[8].TaskValues[0].Value');
var luxc=global.get('nodemcu["192.168.1.63"].Sensors[9].TaskValues[0].Value');
var door=global.get('nodemcu["192.168.1.63].Sensors[8].TaskValues[0].Value');
var doorOut=global.get('nodemcu["192.168.1.63].Sensors[7].TaskValues[0].Value');
var svetc=global.get('nodemcu["192.168.1.63"].Sensors[10].TaskValues[0].Value');
global.set('dom.svet',svett);
global.set('dom.tout',tempOutt);
global.set('dom.svet_k',svetCookk);
global.set('dom.temp_k',tempKk);
global.set('dom.humy',humii);
global.set('dom.co',coo);
global.set('dom.vent',ventVv);
global.set('dom.tema',temaa);
global.set('dom.lux_k',luxk);
global.set('dom.pir_k',pirk);
global.set('dom.lux_k',luxk);
global.set('dom.okno',oknoo);
global.set('dom.utro',utroo);
global.set('dom.lux_c',luxc);
global.set('dom.door_in',door);
global.set('dom.door_out',doorOut);
global.set('dom.led_c',svetc);
var esse=global.get('nodemcu');
msg2.payload = esse;

